<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e0aab009-ef8e-4687-9bf1-62aa456b2e33</elementGuidId>
    <imagePath></imagePath>
    <name>input_requestReplacement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[14]/div[2]/div[2]/div[2]/span[1]/input[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="ReplacementTrailerDiv"] input:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'RequestReplacement') and equals(@name,'RequestReplacement') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#RequestReplacement &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>RequestReplacement</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>RequestReplacement</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>