<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a5e72997-411d-4409-bb7a-93b83b58d71e</elementGuidId>
    <imagePath></imagePath>
    <name>label_removeFromDoor</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[14]/div[2]/div[1]/span[2]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>span:nth-of-type(2) &gt; label</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Remove From Door"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>