<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>17f94b83-2297-4a21-892e-fe63468cf4b3</elementGuidId>
    <imagePath></imagePath>
    <name>link_loadName3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[4]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[30]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="doorNumber-16278"] &gt; .doorLink</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Load Name: 320~1
            Route: 320~1') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#doorNumber-16278 &gt;&gt; internal:text="1"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Load Name: 320~1
        Route: 320~1</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>