<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6be11199-df21-4947-9e05-41e5f76e4133</elementGuidId>
    <imagePath></imagePath>
    <name>span_removeFromDoor</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[14]/div[2]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="rtdPopUp"] &gt; div &gt; span:nth-of-type(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="Remove From Door"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>