<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>04126467-e64a-4ac7-a4cc-ff1ef4e7e2b4</elementGuidId>
    <imagePath></imagePath>
    <name>input_submit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[2]/input[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="submitButtonDialogBox\ button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Dock Layout Reset"i &gt;&gt; internal:text="Submit"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>