<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8fc6c158-36a2-439c-ac96-28b86bf720c7</elementGuidId>
    <imagePath></imagePath>
    <name>div_paymentPrompt</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="modeCash"] &gt; [class="d-flex-grow-1\ margin-left-s"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[2]/div[1]/div[1]/label[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"CashYour prompt payment is\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>