<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff602eac-745e-4f29-bce8-f16d76f181c3</elementGuidId>
    <imagePath></imagePath>
    <name>input_cashPrompt</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#modeCash</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"CashYour prompt payment is\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>