<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f590db7e-2010-4b73-9a22-affea5ae3f0a</elementGuidId>
    <imagePath></imagePath>
    <name>select_planType</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/section[1]/div[1]/div[3]/div[1]/div[1]/section[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[6]/div[1]/div[1]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'PlanType') and equals(@title,'Plan Type')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Plan Type\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>PlanType</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Plan Type</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
</WebElementEntity>