<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>002fe3ca-33ba-4fb4-a404-e80fc4e05ba1</elementGuidId>
    <imagePath></imagePath>
    <name>link_dockLayout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/ul[1]/li[2]/a[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/dock-management/DockLayout') and equals(@text,'Dock Layout')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/dock-management/DockLayout</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Dock Layout</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>