<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3a5a1cd5-172a-484d-9459-46b1058f7bc8</elementGuidId>
    <imagePath></imagePath>
    <name>link_sendEmailRequest</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#sendEmail</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/div[2]/a[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'sendEmail') and equals(@class,'blackButton roundCorners shadow signerChoiceButton') and equals(@href,'/EGApp/eSign/ClientEmail?SignerType=4') and equals(@text,' Send Email Request')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Send Email Request\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>blackButton roundCorners shadow signerChoiceButton</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/EGApp/eSign/ClientEmail?SignerType=4</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>sendEmail</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value> Send Email Request</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>