<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f80f35ff-224e-4e0e-89d8-f527b95cfd20</elementGuidId>
    <imagePath></imagePath>
    <name>link_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ul[3]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="ui-id-380"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ui-id-380') and equals(@text,'{{name}}, {{name}}')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="{{name}}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ui-id-380</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{name}}, {{name}}</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>