<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e7394c77-756a-41fd-a03c-9f89cdbbcdae</elementGuidId>
    <imagePath></imagePath>
    <name>image_noImage</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>app-thumbnail-image:nth-of-type(1) #thumbnail</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/section[1]/app-micro-app[1]/div[1]/div[1]/app-viewer-app[1]/div[1]/app-root[1]/div[1]/app-main-area[1]/div[1]/app-thumbnail-bar[1]/app-toolbar[1]/div[1]/div[2]/div[1]/app-thumbnail-images[1]/app-scroll-overflow[1]/div[1]/app-thumbnail-image[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'thumbnail')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>img[alt=\"no-image\"] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>thumbnail</value>
        <webElementGuid>4af81368-e170-490a-917d-98f5cd3929ad</webElementGuid>
    </webElementProperties>
</WebElementEntity>