<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>52a13843-b1e1-4ae4-b8a0-62f58fc32abb</elementGuidId>
    <imagePath></imagePath>
    <name>tiMultiSelect_object2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#samplebuy-table th:nth-of-type(8) &gt; [class="hydrated"] &gt; [class="hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//div/table[1]/thead[1]/tr[2]/th[8]/ti-column-filter[1]/ti-multi-select[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#samplebuy-table ti-multi-select &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/QA-G3/Page_home/tiOrderNowTable_object2</value>
        <webElementGuid>4af81368-e170-490a-917d-98f5cd3929ad</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>4af81368-e170-490a-917d-98f5cd3929ad</webElementGuid>
    </webElementProperties>
</WebElementEntity>