<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1ac008a5-bfe8-477c-9e98-de29bd04ee16</elementGuidId>
    <imagePath></imagePath>
    <name>button_generateLinkWithoutEmail</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#buttonGenerateLink</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/form[1]/div[2]/table[1]/tbody[1]/tr[3]/td[1]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'buttonGenerateLink') and equals(@class,'{{username}} roundCorners {{username}}') and equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Generate Link Without Email\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>{{username}} roundCorners {{username}}</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>buttonGenerateLink</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>