<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a3ba0c7a-6609-47bd-ab3d-1e887e4f5b21</elementGuidId>
    <imagePath></imagePath>
    <name>button_reSign</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/div[2]/div[2]/ul[1]/li[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Re-Sign\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>