<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>79cebb2e-c7f1-4f3e-88a3-2da3e383da2a</elementGuidId>
    <imagePath></imagePath>
    <name>strong_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/table[1]/tbody[1]/tr[1]/td[3]/div[4]/div[7]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/strong[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.f1bfb8f3-7567-47a5-b6f7-3e43b5b9e063 &gt; div &gt; table &gt; tbody &gt; tr &gt; .top &gt; strong &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>