<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a15fda5d-feb1-40f3-9d0c-4a7ef4edeac4</elementGuidId>
    <imagePath></imagePath>
    <name>td_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/table[1]/tbody[1]/tr[1]/td[3]/div[4]/div[7]/div[1]/table[1]/tbody[1]/tr[1]/td[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.f1bfb8f3-7567-47a5-b6f7-3e43b5b9e063 &gt; div &gt; table &gt; tbody &gt; tr &gt; .top</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>