<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>appPaymentBeneficiaryList_object</name>
   <tag></tag>
   <elementGuidId>54602314-f41f-4364-8551-5c7dc4cc4e86</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/app-payment[1]/div[1]/div[1]/app-payment-details[1]/div[1]/app-payment-details-form[1]/div[1]/app-payment-beneficiary-list[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;grid\ grid-12&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'grid grid-12' and (text() = 'Account holder/policy holder nameSA*** CHAN*** WIJ***Account number*Bank account currency**Rupiah...[truncated lines=9]' or . = 'Account holder/policy holder nameSA*** CHAN*** WIJ***Account number*Bank account currency**Rupiah...[truncated lines=9]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-payment-beneficiary-list</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid grid-12</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account holder/policy holder nameSA*** CHAN*** WIJ***Account number*Bank account currency**Rupiah...[truncated lines=9]</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
