<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_otherInsuranceDetails</name>
   <tag></tag>
   <elementGuidId>44e15297-c702-4d68-a00f-6aa2420a0625</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[2]/app-question-form-input[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherInsuranceDetails .parent-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'parent-content' and (text() = 'Other insurance details' or . = 'Other insurance details')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#otherInsuranceDetails &gt; app-question-form-input &gt; .parent-container &gt; .parent-content</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>parent-content</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other insurance details</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
