<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_customerIdentification7</name>
   <tag></tag>
   <elementGuidId>5f016d1f-8549-40fe-a264-2c64220fa47b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-customer-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;flex\ flex-1\ tb\:flex-col\ mt-12\ px-5\ sm\:px-5\ tb\:px-10\ md\:px-10\ xl\:px-10\ lg\:px-10\ mb-10\ md\:w-3\/5\ lg\:w-3\/5\ xl\:w-3\/5&quot;] > div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '123Customer IdentificationYour policy number is...[truncated lines=7]' or . = '123Customer IdentificationYour policy number is...[truncated lines=7]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.tb\:flex-1 &gt; div &gt; div &gt; div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123Customer IdentificationYour policy number is...[truncated lines=7]</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
