<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_customerIdentification2</name>
   <tag></tag>
   <elementGuidId>54d8b62f-5c80-4a48-97bf-079acdd73db8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-customer-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;flex\ flex-1\ tb\:flex-col\ mt-12\ px-5\ sm\:px-5\ tb\:px-10\ md\:px-10\ xl\:px-10\ lg\:px-10\ mb-10\ md\:w-3\/5\ lg\:w-3\/5\ xl\:w-3\/5&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'flex flex-1 tb:flex-col mt-12 px-5 sm:px-5 tb:px-10 md:px-10 xl:px-10 lg:px-10 mb-10 md:w-3/5 lg:w-3/5 xl:w-3/5' and (text() = '123Customer IdentificationYour policy number is...[truncated lines=7]' or . = '123Customer IdentificationYour policy number is...[truncated lines=7]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.tb\:flex-1 &gt; div &gt; div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 tb:flex-col mt-12 px-5 sm:px-5 tb:px-10 md:px-10 xl:px-10 lg:px-10 mb-10 md:w-3/5 lg:w-3/5 xl:w-3/5</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123Customer IdentificationYour policy number is...[truncated lines=7]</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
