<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_radioTouchTarget</name>
   <tag></tag>
   <elementGuidId>350d87b6-4e7b-44ae-98d0-7fe5e8334d0e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[1]/app-question-form-item[3]/app-question-form-input[1]/div[1]/esub-ui-choice-list[1]/div[1]/esub-ui-radio[1]/cds-radio[1]/mat-radio-group[1]/mat-radio-button[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;mat-radio-29&quot;] .mat-mdc-radio-touch-target</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'mat-mdc-radio-touch-target']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-radio-29 &gt; .mdc-form-field &gt; .mdc-radio &gt; .mat-mdc-radio-touch-target</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-radio-touch-target</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
