<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_uploadedFileItem</name>
   <tag></tag>
   <elementGuidId>2d082272-47e8-4d58-b7d7-5b9e9bd698a0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-supporting-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[3]/app-file-upload[1]/div[1]/div[2]/div[4]/app-file-upload-form[1]/div[1]/app-file-upload-item[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body:nth-of-type(1) > app-root:nth-of-type(1) > div:nth-of-type(1) > app-supporting-information:nth-of-type(1) > app-submission-wizard:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(3) > app-file-upload:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(4) > app-file-upload-form:nth-of-type(1) > div:nth-of-type(1) > app-file-upload-item:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'w-full grid grid-cols-6 gap-y-4 gap-x-6' and (text() = 'KTP2.pdf(190.05KB)×' or . = 'KTP2.pdf(190.05KB)×')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) &gt; app-file-upload-form &gt; .document-content &gt; app-file-upload-item &gt; .inset-0 &gt; .sm\:flex-none &gt; div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full grid grid-cols-6 gap-y-4 gap-x-6</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KTP2.pdf(190.05KB)×</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
