<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_choiceListPlaceOfDeath</name>
   <tag></tag>
   <elementGuidId>68e03409-6020-423e-8bb8-2cd962674e93</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[1]/app-question-form-item[2]/app-question-form-input[1]/div[1]/esub-ui-choice-list[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;form-input-container\ Choice\ placeOfDeath\ ng-star-inserted&quot;] .choice-list-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'choice-list-container relative' and (text() = 'Place of deathHospitalHome' or . = 'Place of deathHospitalHome')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.choice-list-container >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choice-list-container relative</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place of deathHospitalHome</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
