<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_upload7</name>
   <tag></tag>
   <elementGuidId>a8051821-edc2-41fd-ae56-0ddeefa4a1f4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-supporting-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[3]/app-file-upload[1]/div[1]/div[2]/div[4]/app-file-upload-form[1]/div[1]/app-file-upload-input[1]/div[1]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body:nth-of-type(1) > app-root:nth-of-type(1) > div:nth-of-type(1) > app-supporting-information:nth-of-type(1) > app-submission-wizard:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(3) > app-file-upload:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(4) > app-file-upload-form:nth-of-type(1) > div:nth-of-type(1) > app-file-upload-input:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > label:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'tb:absolute md:absolute lg:absolute xl:absolute cursor-pointer' and (text() = 'Upload' or . = 'Upload')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) &gt; app-file-upload-form &gt; .document-content &gt; app-file-upload-input &gt; .file-upload-input-container &gt; .block &gt; .tb\:absolute</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tb:absolute md:absolute lg:absolute xl:absolute cursor-pointer</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
