<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_acuteAbdomen2</name>
   <tag></tag>
   <elementGuidId>d8dcce85-8bf9-4a0a-b01c-d984d38b6b02</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-input[1]/div[1]/esub-ui-multiselect-dropdown[1]/div[1]/div[1]/ng-autocomplete[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > [class=&quot;ng-star-inserted&quot;] > [class=&quot;ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ng-star-inserted' and (text() = 'Acute abdomen' or . = 'Acute abdomen')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:text=&quot;Acute abdomen&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acute abdomen</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
