<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_anZpaninBank3</name>
   <tag></tag>
   <elementGuidId>ef9df441-28b8-4440-91ac-05566af9b609</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/app-payment[1]/div[1]/div[1]/app-payment-details[1]/div[1]/app-payment-details-form[1]/div[1]/app-payment-beneficiary-list[1]/div[1]/div[1]/app-payment-beneficiary-account[1]/div[1]/div[4]/app-autocomplete-dropdown[1]/esub-ui-autocomplete-dropdown[1]/div[1]/ng-autocomplete[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > [class=&quot;ng-star-inserted&quot;] > [class=&quot;ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ng-star-inserted' and (text() = 'ANZ PANIN BANK' or . = 'ANZ PANIN BANK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:text=&quot;ANZ PANIN BANK&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ANZ PANIN BANK</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
