<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>matRadioGroup_eventCause</name>
   <tag></tag>
   <elementGuidId>35991971-3057-4024-b8d8-5470b6d4af84</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-event[1]/div[1]/div[1]/app-claim-event-cause[1]/div[1]/div[1]/app-radio-button[1]/cds-radio[1]/mat-radio-group[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;cds-radio-2&quot;] > .mat-mdc-radio-group</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'mat-mdc-radio-group ng-valid ng-touched ng-dirty' and (text() = 'AccidentIllness' or . = 'AccidentIllness') and @role = 'radiogroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cds-radio-2 mat-radio-group</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-radio-group ng-valid ng-touched ng-dirty</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radiogroup</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AccidentIllness</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
