<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_calendarDay13</name>
   <tag></tag>
   <elementGuidId>04a5930d-1781-435c-b4ec-1a7160f21c6b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-item[2]/app-question-form-item[2]/app-question-form-input[1]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[1]/cds-calendar[1]/div[1]/cds-calendar-month[1]/section[3]/cds-calendar-item[4]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body:nth-of-type(1) > app-root:nth-of-type(1) > div:nth-of-type(1) > app-claim-information:nth-of-type(1) > app-submission-wizard:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(4) > app-claim-questions:nth-of-type(1) > app-questionnaire:nth-of-type(1) > app-question-form-list:nth-of-type(1) > app-question-form-item:nth-of-type(1) > app-question-form-item:nth-of-type(1) > app-question-form-item:nth-of-type(1) > app-question-form-item:nth-of-type(2) > app-question-form-item:nth-of-type(2) > app-question-form-input:nth-of-type(1) > div:nth-of-type(1) > esub-daterange-picker:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > cds-calendar:nth-of-type(1) > div:nth-of-type(1) > cds-calendar-month:nth-of-type(1) > section:nth-of-type(3) > cds-calendar-item:nth-of-type(4) > span:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cds-calendar-item__content' and (text() = '11' or . = '11')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section:nth-child(3) &gt; cds-calendar-item:nth-child(4) &gt; .cds-calendar-item__content >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-calendar-item__content</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
