<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_closeFileUpload</name>
   <tag></tag>
   <elementGuidId>55aa8055-aa07-4342-be37-749842e0bc1a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/div[1]/div[1]/mat-option[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;mat-mdc-option\ mdc-list-item\ cds-option&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'm-auto justify-end text-navy-500 text-basex2 font-semibold cursor-pointer' and (text() = '×' or . = '×')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-option-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto justify-end text-navy-500 text-basex2 font-semibold cursor-pointer</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
