<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_removeFile3</name>
   <tag></tag>
   <elementGuidId>8cdec53a-d714-4fbf-9d1d-1229eea5016b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-supporting-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[3]/app-file-upload[1]/div[1]/div[2]/div[3]/app-file-upload-form[1]/div[1]/app-file-upload-item[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body:nth-of-type(1) > app-root:nth-of-type(1) > div:nth-of-type(1) > app-supporting-information:nth-of-type(1) > app-submission-wizard:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(3) > app-file-upload:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(3) > app-file-upload-form:nth-of-type(1) > div:nth-of-type(1) > app-file-upload-item:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > span:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'm-auto justify-end text-navy-500 text-basex2 font-semibold cursor-pointer' and (text() = '×' or . = '×')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) &gt; app-file-upload-form &gt; .document-content &gt; app-file-upload-item &gt; .inset-0 &gt; .sm\:flex-none &gt; div &gt; .col-span-6 &gt; .file-upload-box &gt; span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto justify-end text-navy-500 text-basex2 font-semibold cursor-pointer</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>88f339b4-62fd-49a4-9179-a6d21e1e2e90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
