<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93a2db76-9e72-4e3c-9b7f-fff30647dd7e</elementGuidId>
    <imagePath></imagePath>
    <name>div_creditCardPayment</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="modeCredit"] &gt; [class="d-flex-grow-1\ margin-left-s"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"Credit CardPay with Visa,\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>