<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>42708fa8-e4e6-4a2e-95f7-4ac9dd0db037</elementGuidId>
    <imagePath></imagePath>
    <name>div_creditCard</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="checkout-fieldset-collapse\ "]:nth-child(4) [class="checkout-checkbox-field"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#app div &gt;&gt; internal:has-text=\"Credit CardPay with Visa,\"i &gt;&gt; nth=3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>