<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e5a4e49f-500e-49a1-9020-ff799949db49</elementGuidId>
    <imagePath></imagePath>
    <name>header_shippingInfo</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="d-flex-grow-1\ margin-0"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[3]/div[1]/div[1]/label[1]/h5[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name=\"International Shipping 7-14\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>