<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee1029dd-7213-431b-949e-2e20c7403769</elementGuidId>
    <imagePath></imagePath>
    <name>input_passwordPlaceholder</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#ccv</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[2]/div[2]/div[2]/div[2]/div[1]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder=\"****\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>