<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3b5c17ee-e199-4ae5-81bc-a5bde6470ad3</elementGuidId>
    <imagePath></imagePath>
    <name>input_namePlaceholder</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#name</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder=\"Jane Doe\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>