<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a401bdd-331a-4fdf-adba-b6e0088c78c7</elementGuidId>
    <imagePath></imagePath>
    <name>input_shippingOption</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#isInternational</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Shipping Option\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>