<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2357f95b-3adf-4323-bdd6-c66d4d4f6089</elementGuidId>
    <imagePath></imagePath>
    <name>span_paymentPrompt</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="modeCash"] [class="text-subtle\ d-block\ margin-top-s"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[2]/div[1]/div[1]/label[1]/div[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"Your prompt payment is\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>