<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c718feb7-b7b1-4e84-b3a6-ec28498fb368</elementGuidId>
    <imagePath></imagePath>
    <name>span_paymentMethods</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="modeCredit"] [class="text-subtle\ d-block\ margin-top-s"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/div[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"Pay with Visa, Master Card\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>