<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b53fd202-8079-4e05-bd80-b927d92e6c01</elementGuidId>
    <imagePath></imagePath>
    <name>span_decreaseQuantity</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="anticon\ anticon-minus"] &gt; svg</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/span[1]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name=\"minus\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>