<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ba0f4f2d-642e-4bb5-9ce3-de6f74a97709</elementGuidId>
    <imagePath></imagePath>
    <name>td_osdExceptionPieces</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[5]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.even &gt; td:nth-of-type(6)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.even &gt; td:nth-child(6)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>