<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd924287-7979-4f17-b8de-3505306cf17d</elementGuidId>
    <imagePath></imagePath>
    <name>div_object2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="Display-0"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/section[1]/app-micro-app[1]/div[1]/div[1]/app-viewer-app[1]/div[1]/app-root[1]/div[1]/app-main-area[1]/div[1]/div[1]/app-image-display-grid[1]/div[1]/div[1]/app-image-display-wrapper[1]/app-image-display-element[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#Display-0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>