<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f35f4480-0eee-49d9-8258-ce2e840013b3</elementGuidId>
    <imagePath></imagePath>
    <name>link_object7</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="navigation-menu-main"] &gt; li:nth-child(2) &gt; a</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/nav[2]/ul[1]/li[2]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name=\"Shop\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/GH_ACTION/Page_home/ti_multiSelectObject2</value>
        <webElementGuid>46234098-f8ba-49ce-ba02-34a77cdfa3b9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>46234098-f8ba-49ce-ba02-34a77cdfa3b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>