<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1d9102e2-df4c-4bf2-8638-c20d73fd4f34</elementGuidId>
    <imagePath></imagePath>
    <name>ti_multiSelectObject</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#samplebuy-table th:nth-of-type(8) &gt; [class="hydrated"] &gt; [class="hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//div/table[1]/thead[1]/tr[2]/th[8]/ti-column-filter[1]/ti-multi-select[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#samplebuy-table ti-multi-select &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/GH_ACTION/Page_home/ti_orderNowTableObject</value>
        <webElementGuid>46234098-f8ba-49ce-ba02-34a77cdfa3b9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>46234098-f8ba-49ce-ba02-34a77cdfa3b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>