<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bbe265cf-bc53-438d-8269-5df97f8f292f</elementGuidId>
    <imagePath></imagePath>
    <name>ti_orderNowTableObject2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti-order-now-table-all\ hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[6]/ti-order-now-table[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-order-now-table</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>