<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8606a325-3bd0-4886-99e5-a236a9b0bd44</elementGuidId>
    <imagePath></imagePath>
    <name>ti_orderNowTableObject</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti-order-now-table-all\ hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[6]/div[2]/ti-order-now-table[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-order-now-table</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>