<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>68cda408-a55b-4488-ba6f-4cbc578aee72</elementGuidId>
    <imagePath></imagePath>
    <name>link_documentManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[3]/div[1]/div[1]/div[2]/nav[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}?AppGuid={{url}}#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"${link_documentManagement_internalText}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}?AppGuid={{url}}#</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
</WebElementEntity>