<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>10f9cb3a-5e77-4e22-913a-a451347b4eba</elementGuidId>
    <imagePath></imagePath>
    <name>button_ok</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[12]/div[11]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ui-button\ ui-widget\ ui-state-default\ ui-corner-all\ ui-button-text-only\ ui-state-focus\ ui-state-hover"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Ok')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Info"i &gt;&gt; button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Ok</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>