<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d91d7468-15da-4e0e-970b-1886c7abb6d2</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/div[16]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[13]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ConfirmReviewBtn\ button"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Check In"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>