<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e4813cc5-4f90-4e8b-8fac-5233869ecea2</elementGuidId>
    <imagePath></imagePath>
    <name>link_pdcheckIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/ul[1]/li[5]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(5) &gt; #nav-col-container li:nth-of-type(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/dock-management/PnD/PDMorningCheckIn') and equals(@text,'P&amp;D Morning Check-in')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="P&amp;D Morning Check-in"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/dock-management/PnD/PDMorningCheckIn</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>P&amp;D Morning Check-in</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>