<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>797a0482-70d3-45e9-aae8-2947df98c6bb</elementGuidId>
    <imagePath></imagePath>
    <name>link_create4</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="blackButton\ roundCorners\ shadow\ createAppModal"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/div[2]/form[1]/div[1]/div[4]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'buildNew') and equals(@class,'blackButton roundCorners shadow createAppModal') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Create\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>blackButton roundCorners shadow createAppModal</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>buildNew</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>