<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7ed31c2c-3e83-4376-9a30-8844b3f4d94a</elementGuidId>
    <imagePath></imagePath>
    <name>link_annuityFlaccessCarrier2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>a:nth-of-type(184)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/div[3]/a[184]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'listProd grayButton roundCorners shadow') and equals(@href,'#') and equals(@text,'Annuity FL Access Carrier - Automation Product With Small &amp; Long Signer Names')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Annuity FL Access Carrier - Automation Product With Small &amp; Long Signer Names\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>listProd grayButton roundCorners shadow</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Annuity FL Access Carrier - Automation Product With Small &amp; Long Signer Names</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>