<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe5a62e7-666c-41ea-b363-c96e6eb9538f</elementGuidId>
    <imagePath></imagePath>
    <name>iframe_object4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[12]/div[2]/iframe[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#iframe</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#iframe</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>