<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7e56d832-2a90-437c-8d5d-b66f845dcd6f</elementGuidId>
    <imagePath></imagePath>
    <name>link_dockManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[4]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${link_dockManagement_id}"] &gt; .doorLink</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Close To: BOS
            Dispatch To: BOS
            Load Name: 
            Destinations: BOS-PRE') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="${link_dockManagement_internalText}"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Close To: BOS
        Dispatch To: BOS
        Load Name: 
        Destinations: BOS-PRE</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>