<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ac97a55-a26a-4b84-b12b-f029dcd60514</elementGuidId>
    <imagePath></imagePath>
    <name>link_doorLoadData</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[4]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="DoorDescription-36\ fullHeight\ CurrentLoadingPoints\ Yellow\ loadToDrag\ loadToCell1\ ui-draggable"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Close To: NBG
            Dispatch To: NBG
            Load Name: 
            Destinations: ABL, ABQ, AMA, BAL-PRE, BSS, BUZ, DLS, ELP, HAG-PRE, IVG, KAN, KSL, LAF, LAO, LRA, LVE, MEM-PRE, NOR-PRE, ODE, RAB, REP, RNO, ROS, SNA, TRG-PRE, TTX, VMW-PRE, VVA-PRE, WIC, XPX-PRE, YOU-PRE') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="${link_doorLoadData_internalText}"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Close To: NBG
        Dispatch To: NBG
        Load Name: 
        Destinations: ABL, ABQ, AMA, BAL-PRE, BSS, BUZ, DLS, ELP, HAG-PRE, IVG, KAN, KSL, LAF, LAO, LRA, LVE, MEM-PRE, NOR-PRE, ODE, RAB, REP, RNO, ROS, SNA, TRG-PRE, TTX, VMW-PRE, VVA-PRE, WIC, XPX-PRE, YOU-PRE</value>
        <webElementGuid>0aadffd4-3938-4fe9-bd9a-5462736363e0</webElementGuid>
    </webElementProperties>
</WebElementEntity>