<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3f137e5f-86a6-4d58-a540-7d9a21fc858a</elementGuidId>
    <imagePath></imagePath>
    <name>button_addToBasket</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="product-card-button\ button-small\ button\ button-block\ "]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name=\"Add to basket\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>