<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4ac8c9f0-0717-44ee-baf4-a62dabf3331c</elementGuidId>
    <imagePath></imagePath>
    <name>header_productName</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="product-card-name\ text-overflow-ellipsis\ margin-auto"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[2]/h5[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name=\"Philodendron Imperial Red\"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>