<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>689ef30f-fa43-4812-b7ca-3e19e57284fb</elementGuidId>
    <imagePath></imagePath>
    <name>input_searchProduct</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="search-input\ searchbar-input"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[2]/input[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder=\"Search product...\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>