<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4f4ba132-3e7b-4a3a-b91d-d36b54ed33a6</elementGuidId>
    <imagePath></imagePath>
    <name>span_shoppingButton</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="anticon\ anticon-shopping"] &gt; svg</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[1]/button[1]/div[1]/span[1]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name=\"shopping\"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>