<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>03fc4593-d69e-4050-99f3-346058cc998e</elementGuidId>
    <imagePath></imagePath>
    <name>div_dropdownIndicator</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/div[4]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'9109c756-177a-44cb-995d-ab838f656d480')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#divForms div &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>9109c756-177a-44cb-995d-ab838f656d480</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
</WebElementEntity>