<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fddb3bb1-5112-4765-bc13-f9b5543ebf82</elementGuidId>
    <imagePath></imagePath>
    <name>select_productType7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[2]/div[2]/form[1]/div[1]/label[1]/select[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ProductType') and equals(@name,'ProductType')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Product Type: Select Product Type All Annuity Deferred Income Annuity Fixed Annuity Fixed Indexed Annuity Immediate Annuity Multi-Year Guaranteed Annuity Single Premium Immediate Annuity\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ProductType</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>ProductType</value>
        <webElementGuid>57305005-1f28-43a0-95c8-a7d4dc4c055c</webElementGuid>
    </webElementProperties>
</WebElementEntity>