<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8c90a39a-e878-4dba-bdd3-7e160f78e36c</elementGuidId>
    <imagePath></imagePath>
    <name>link_logOff2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.roundCornersRight</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[3]/div[1]/div[1]/div[2]/nav[1]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'blueButton toolbarButton shadow roundCornersRight') and equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Log Off\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>blueButton toolbarButton shadow roundCornersRight</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>eb99db63-9b4d-442e-88fe-52afb3ffee0c</webElementGuid>
    </webElementProperties>
</WebElementEntity>